card/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'card.views.index', name="index"),
    url(r'^confirmar/$', 'card.views.confirm', name="data-confirm"),
)

handicapcard/urls.py
from django.conf.urls import patterns, include, url
#from django.views.generic.simple import direct_to_template
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'card.views.root_index', name='root-index'),
    url(r'^tarjeta/', include('card.urls')),
    url(r'^faq/$', TemplateView.as_view(template_name= 'faq.html'), name='faq'),
    url(r'^secretaria-movilidad/$', TemplateView.as_view(template_name= 'movilidad.html'), name='movilidad'),
    url(r'^secretaria-salud/$', TemplateView.as_view(template_name= 'salud.html'), name='salud'),
    url(r'^secretaria-integracion-social/$', TemplateView.as_view(template_name= 'integracion.html'), name='integracion'),
    url(r'^cita/', include('appointment.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^archivo/$', 'file.views.login', name='login'),
    #url(r'^archivo/logout$', 'file.views.logout', name='logout'),
    #url(r'^archivo/carga$', 'file.views.archivo', name='archivo'),
    url(r'^archivo/$', 'file.views.archivo', name='archivo'),
)

card/models.py
# -*- coding: utf-8 -*-
from django.db import models

DOCUMENTS_CHOICES = (
    ("AS", u"Adulto sin identificar"),
    ("CC", u"Cédula de Ciudadania"),
    ("CE", u"Cédula de Extranjeria"),
    ("MS", u"Menor sin Identificar"),
    ("PA", u"Pasaporte"),
    ("RC", u"Registro Civil"),
    ("TI", u"Tarjeta de Identidad"),
)

LOCALITIES_CHOICES = (
    (1, "Usaquen"),
    (2, "Chapiner"),
    (3, "Santafe"),
    (4, "San Cristobal"),
    (5, "Usme"),
    (6, "Tunjuelito"),
    (7, "Bosa"),
    (8, "Kennedy"),
    (9, "Fontibon"),
    (10, "Engativa"),
    (11, "Suba"),
    (12, "Barrios Unidos"),
    (13, "Teusaquillo"),
    (14, "Los Martires"),
    (15, "Antonio Narino"),
    (16, "Puente Aranda"),
    (17, "La Candelaria"),
    (18, "Rafael Uribe"),
    (19, "Ciudad Bolivar"),
    (20, "Sumapaz"),
)

DEATH_CHOICES = (
    ("1", "Viva"),
    ("2", "Fallecida"),
)

SDM_CHOICES = (
    ("1", "Exceptuado por Pico y Placa"),
    ("2", "propietario de vehiculo"),
    ("3", "por solicitud del beneficiario"),
)

EXCLUED_KEYS = (
    'created_at', 
    'updated_at',
    '_state',
)

VALID_CHOICE=[]
for choice in SDM_CHOICES:
    VALID_CHOICE.append(choice[0])

class Card(models.Model):
    card_kind = models.CharField(max_length=200)
    person = models.OneToOneField("Person", blank=True, null=True)

class Vehicle(models.Model):
    license_plate = models.CharField(max_length=10, blank=True, null=True)
    transit_entity = models.CharField(max_length=300, blank=True, null=True)

    def __unicode__(self):
        return u"{0.license_plate}".format(self)

class Person(models.Model):
    record_day = models.PositiveSmallIntegerField()
    record_month = models.PositiveSmallIntegerField()
    record_year = models.PositiveSmallIntegerField()
    first_name = models.CharField(max_length=300)
    second_name = models.CharField(max_length=300, blank=True, null=True)
    last_name = models.CharField(max_length=300)
    last_name_second = models.CharField(max_length=300, blank=True, null=True)
    kind_document = models.CharField(max_length=2, choices=DOCUMENTS_CHOICES)
    document = models.CharField(max_length=200, unique=True)
    birth_day = models.DateField()
    address = models.CharField(max_length=500, blank=True, null=True)
    locality = models.PositiveSmallIntegerField(choices=LOCALITIES_CHOICES)
    neighborhood = models.CharField(max_length=300, blank=True, null=True)
    is_death = models.CharField(max_length=1, choices=DEATH_CHOICES, default="2")
    vehicles = models.ManyToManyField('Vehicle', blank=True, null=True, related_name='owner')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"{0.kind_document} {0.document} - {0.first_name} {0.second_name} {0.last_name} {0.last_name_second}".format(self)

    def __eq__(self, other):
        return self._compare(self, other)

    def __ne__(self, other):
        return not self._compare(self, other)

    def _compare(self, obj1, obj2):
        d1, d2 = obj1.__dict__, obj2.__dict__
        for k, v in d1.items():
            if k in EXCLUED_KEYS:
                continue
            try:
                if v != d2[k] :
                    return False
            except KeyError:
                raise RuntimeError('Invalid property {p} in {o}'.format(p=k, o=d2))
        return True
                


class Novelty(models.Model):
    sdm = models.CharField(max_length=1, choices=SDM_CHOICES, blank=True, null=True)
    person = models.ForeignKey('Person', related_name='novelties')

    def save(self, force_insert=False, force_update=False):
        if self.sdm in VALID_CHOICE:
            models.Model.save(self, force_insert, force_update)

card/forms.py
# -*- coding: utf-8 -*-
from django import forms

from card.models import DOCUMENTS_CHOICES

class SearchForm(forms.Form):
    kind_document = forms.ChoiceField(choices=(('','Seleccione un tipo de documento'),)+DOCUMENTS_CHOICES, label=u"Tipo de identificación")
    document = forms.CharField(max_length=200, label=u"Identificación")
    

class ConfirmationForm(forms.Form):
    person_id = forms.IntegerField(widget=forms.HiddenInput)
    person_document = forms.CharField(max_length=200, widget=forms.HiddenInput)
    confirm = forms.BooleanField(required=False, widget=forms.HiddenInput)

card/views.py
from django.shortcuts import render, redirect

from appointment.forms import AppointmentStep1
from card.forms import SearchForm, ConfirmationForm
from card.models import Person

def user_have_card(person):
    import MySQLdb
    KINDS_MAP = {
        "CC": 151,
        "CE": 153,
        "PA": 156,
        "RC": 155,
        "TI": 154,
    }
    connection_params = {
        'host': "sisu-db.cfuphjwmez2w.us-east-1.rds.amazonaws.com",
        #'host': "portalweb-db.cr0k1tnuhdai.us-west-2.rds.amazonaws.com",
        'user': "sisudb",
        'passwd': "SXuWTiiNKX67kXP",
        'db': "sisudb",
    }
    if person.kind_document in KINDS_MAP:
        db = MySQLdb.connect(**connection_params)
        query_str = """
        select PrmTipoIdentificacion, Identificacion, PrmPoblacionEspecial 
        from PtrSolicitudesPersonalizacion
        where PrmTipoIdentificacion={kind_document} and Identificacion={document}
        LIMIT 1
        """.format(kind_document=KINDS_MAP[person.kind_document], document=person.document)
        db.query(query_str)
        result = db.store_result()
        for row in result.fetch_row(how=1):
            if row['PrmPoblacionEspecial'] == 1359:
                return True, True
            return True, False
    return False, False

def index(request):
    context = {}
    MSG_NOBD = False # No esta en la BD
    MSG_PYP = False # Pico y placa
    MSG_VHCL = False # propietario
    MSG_CHC = False
    MSG_DTH = False # fallecido
    
    if request.method == "POST":
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            kd = search_form.cleaned_data['kind_document']
            d = search_form.cleaned_data['document']
            qs = Person.objects.all().filter(kind_document=kd, document=d)
            if qs.exists():
                person = qs[0]
                context['person'] = person
                # context['show_person_data'] = True
                
                if person.novelties.filter(sdm="1").exists():
                    MSG_PYP = True
                    search_form = None
                elif person.novelties.filter(sdm="2").exists():
                    search_form = None
                    MSG_VHCL = True
                    plates = [v.license_plate for v in person.vehicles.all()]
                    vehicles_count = person.vehicles.all().count()
                    plates = list(set(plates))
                    vehicles_count=len(plates)
                    context['plates'] = plates
                    context['vehicles_count'] = vehicles_count
                elif person.novelties.filter(sdm="3").exists():
                    search_form = None
                    MSG_CHC = True
                elif person.is_death == "2":
                    search_form = None
                    MSG_DTH = True
                else:
                    context['person'] = person
                    context['show_person_data'] = True
                    confirmation_form = ConfirmationForm(
                            initial = {
                                    'person_id': person.id,
                                    'person_document': person.document,
                                    'confirm' : True,
                                }
                        )
                    context['confirmation_form'] = confirmation_form
            else:
                search_form = None
                MSG_NOBD = True
    else:
        search_form = SearchForm()

    context['search_form'] = search_form
    context['MSG_NOBD'] = MSG_NOBD
    context['MSG_PYP'] = MSG_PYP
    context['MSG_VHCL'] = MSG_VHCL
    context['MSG_CHC'] = MSG_CHC
    context['MSG_DTH'] = MSG_DTH
    return render(request, "card/index.html", context)

def confirm(request):
    MSG_ID = False # Mensaje de datos incorrectos
    context = {}
    if request.method == "POST":
        confirmation_form = ConfirmationForm(request.POST)
        if confirmation_form.is_valid():
            person_id = confirmation_form.cleaned_data['person_id']
            person_document = confirmation_form.cleaned_data['person_document']
            confirm = confirmation_form.cleaned_data['confirm']
            if confirm:
                #person_qs = Person.objects.all().filter(id=person_id, document=person_document)
                #if person_qs.exists():
                    #have_card, is_senior_card = user_have_card(person_qs[0])
                    context['have_card'] = 'have_card'
                    context['is_senior_card'] = 'have_card'
                    appointment_step1_form = AppointmentStep1(initial=request.POST)
                    context['appointment_step1_form'] = appointment_step1_form
                    return render(request, "appointment/schedule.html", context)
                #else:
                    # El formulario de confirmacion ha sido jaqueado
                #    return redirect('index')
            else:
                MSG_ID = True
                context['MSG_ID'] = MSG_ID
                return render(request, "card/index.html", context)
        else:
            return redirect('index')
    else:
        return redirect('index')

def root_index(request):
    return redirect('index')

card/templates/card/index.html
{% extends "base.html" %}
{% block content %}
<div id="tl_content">
    <div id="tl_Intleft">
        {% if show_person_data %}
        <br>Usted aparece en el registro para obtener la tarjeta tullave con el perfil de Discapacidad:<br>
            <script>
            function wrong() {
              
              document.getElementById('confirm_form').onsubmit = function() {
                var txt = document.getElementById('id_confirm');
                txt.value = "False";
              };
            };
            </script>
            <br><p>Tipo de Documento:   {{ person.get_kind_document_display }}</p>
            <br><p>Identificación:      {{ person.document }}</p>
            <br><p>Nombres:             {{ person.first_name }} {{ person.second_name }}</p>
            <br><p>Apellidos:           {{ person.last_name}} {{ person.last_name_second }}</p>
            <br><br>¿La información es correcta?
            <form action="{% url  'data-confirm' %}" method="POST" id="confirm_form">
                {% csrf_token %}
                {{ confirmation_form.as_p }}
                <input type="submit" value="Si, la información es correcta" size="20">
                <input type="submit" value="No, la información es errada" size="20" onclick="wrong();">
            </form>
        {% else %}
            {% if MSG_NOBD %}
                <hr>
                <p><font color="FF0000">Respetado usuario, usted no se encuentra registrado en la base de datos de la Secretar&iacute;a Distrital de Salud. Puede acercarse a <a href="{% url  'salud' %}" target="none">cualquiera de los puntos de la Secretar&iacute;a</a> para solicitar la inclusi&oacute;n de sus datos</font></p>
                <hr>
            {% endif %}
            {% if MSG_PYP %}
                {% include "card/person.html" %}
                <hr>
                <p> <font color="FF0000">Respetado usuario, usted se encuentra registrado en la base de datos de la Secretaría Distrital de Salud pero se encuentra registrado en la Secretaría Distrital de Movilidad como con beneficio de Pico y Placa. Por esta razón, no pude gozar del beneficio del subsidio de discapacidad. Si la información aquí reflejada es errada, por favor acerquese a <a href="{% url  'movilidad' %}">los puntos de la Secretaría de Movilidad</a> para solicitar la corrección de sus datos.</font></p>
                <hr>
            {% endif %}
            {% if MSG_VHCL %}
                {% include "card/person.html" %}
                <hr>
                <p><font color="ff0000">Respetado usuario, usted se encuentra registrado en la base de datos de la Secretar&iacute;a Distrital de Salud pero se encuentra registrado en la Secretar&iacute;a Distrital de Movilidad como propietario de {{ vehicles_count }} veh&iacute;culo{{ vehicles_count|pluralize }} de placas {% for plate in plates %}{{ plate }} {% endfor %}. Por esta raz&oacute;n, no pude gozar del beneficio del subsidio de discapacidad. Si la informaci&oacute;n aqu&iacute; reflejada es errada, por favor acerquese a <a href="{% url  'movilidad' %}" target="none">cualquiera de los puntos de la Secretar&iacute;a de Movilidad</a> para solicitar la correcci&oacute;n de sus datos.</font></p>
                <hr>
            {% endif %}
            {% if MSG_CHC %}
                {% include "card/person.html" %}
                <hr>
                <p><font color="ff0000">Usted decidió ser excluido de este beneficio. Si quiere cambiar este estado puede acercarse <a href="{% url  'movilidad' %}">los puntos de la Secretaría de Movilidad</a></font></p>
                <hr>
            {% endif %}
            {% if MSG_DTH %}
                {% include "card/person.html" %}
                <hr>
                <p><font color="ff0000">Respetado usuario, usted aparece registrado en la base de datos de la Secretaría de Salud como fallecido. Puede acercarse a <a href="{% url  'salud' %}" target="none">un punto de su localidad de la Secretar&iacute;a de Salud</a> para corregir su registro</font></p>
                <hr>
            {% endif %}
            {% if MSG_ID %}
                <hr>
                <p><font color="ff0000">Respetado usuario, por favor acerquese a <a href="{% url  'salud' %}" target="none">un punto de su localidad de la Secretar&iacute;a de Salud</a> para solicitar la correcci&oacute;n de sus datos.</font></p>
                <hr>
            {% endif %}
            {% if search_form %}
            <p>A través de este sitio, usted puede consultar si aplica para obtener su tarjeta tullave con el
            perfil de discapacidad. Lo invitamos a visitar nuestra página de  <a href="{% url  'faq' %}"> preguntas frecuentes</a>  para conocer más sobre este beneficio.</p>
            <br>
            <h1>Por favor, digite su identificación</h1>
                <form action="{% url  'index' %}" method="post">
                    {% csrf_token %}
                    {{ search_form.as_p }}
                   <input type="submit" value="Buscar" size="20">
                </form>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

card/templates/card/person.html
<br><p>Tipo de Documento:   {{ person.get_kind_document_display }}</p>
<br><p>Identificación:      {{ person.document }}</p>
<br><p>Nombres:             {{ person.first_name }} {{ person.second_name }}</p>
<br><p>Apellidos:           {{ person.last_name}} {{ person.last_name_second }}</p>
<br><br>
<p>Si encuentra un error en sus datos por favor acerquese al <a href="{% url 'salud' %}" target="none">punto de su localidad de la Secretar&iacute;a</a> para solicitar la actualización de los mismos</font></p>
<br><br>